services:
  web:
    build: .
    image: castilloari/vindell:dev  # Imagen con tag de desarrollo
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./pdf_output:/app/pdf_output
      - .:/app  # Montar el directorio actual en /app dentro del contenedor
    restart: unless-stopped
