services:
  web:
    image: castilloari/vindell:latest
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./pdf_output:/app/pdf_output
