# Generated by Django 5.1.2 on 2025-03-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.service')),
            ],
        ),
    ]
