# Generated by Django 5.1.2 on 2025-03-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='RUC',
            field=models.CharField(default='None', max_length=13),
        ),
    ]
