# Generated by Django 5.1.2 on 2025-03-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_invoiceservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
