# Generated by Django 5.1.2 on 2025-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_invoice_client_invoice_provider_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='print_number',
            field=models.PositiveIntegerField(),
        ),
    ]
