# Generated by Django 5.1.2 on 2025-03-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_remove_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
