# Generated by Django 5.1.2 on 2025-03-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_remove_invoice_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceService',
        ),
    ]
